import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { renderHook, waitFor } from "@testing-library/react";
import { delay, HttpResponse, http } from "msw";
import { createElement, type ReactNode } from "react";
import type { BatchUploadResponse } from "../../src/api";
import { ApiError } from "../../src/api";
import {
  classifyUpload,
  uploadDocument,
  useUploadBooks,
} from "../../src/api/uploads";
import {
  batchNotEnabledEnvelope,
  documentsListHandler,
  internalErrorEnvelope,
  libraryBookDetails,
  libraryBookList,
  missingFileEnvelope,
  type ObservedUpload,
  unsupportedFileTypeEnvelope,
  uploadBatchErrorHandler,
  uploadBatchHandler,
  uploadDocumentHandler,
  uploadErrorHandler,
  uploadedDocument,
} from "../msw/handlers";
import { server } from "../msw/server";

/* jsdom multipart limit (see handlers.ts): assertions below stick to field
   names, part counts and scalar values — never filenames or file bytes. */

const pdfFile = (name = "book.pdf") =>
  new File([new Uint8Array([0x25, 0x50, 0x44, 0x46, 0x2d])], name, {
    type: "application/pdf",
  });

describe("uploadDocument", () => {
  it("posts multipart with file + category=recipes and resolves the response", async () => {
    const document = uploadedDocument("book-new", "A Brand New Book");
    let observed: ObservedUpload | null = null;
    server.use(uploadDocumentHandler(document, (o) => (observed = o)));

    const response = await uploadDocument(pdfFile());

    expect(response.document.id).toBe("book-new");
    expect(response.ingestion.status).toBe("queued");
    expect(observed).not.toBeNull();
    const seen = observed as unknown as ObservedUpload;
    expect(seen.fieldNames).toEqual(["file", "category"]);
    expect(seen.category).toBe("recipes");
    /* Positive assertion — "no JSON content-type" would also pass if the
       header were missing for the wrong reason. Boundary is generated by
       the fetch implementation under jsdom; "browser-set" is only
       demonstrable live. */
    expect(seen.contentType).toMatch(/^multipart\/form-data; boundary=/);
  });

  it("rejects a 415 with the typed unsupported_file_type ApiError", async () => {
    server.use(uploadErrorHandler(415, unsupportedFileTypeEnvelope));

    const err = await uploadDocument(pdfFile("pretending.txt")).catch(
      (e: unknown) => e,
    );

    expect(err).toBeInstanceOf(ApiError);
    const apiError = err as ApiError;
    expect(apiError.code).toBe("unsupported_file_type");
    expect(apiError.message).toBe("Only PDF uploads are supported.");
    expect(apiError.details).toEqual({ expected: "application/pdf" });
    expect(apiError.status).toBe(415);
  });

  it("rejects a 400 with the typed invalid_request ApiError", async () => {
    server.use(uploadErrorHandler(400, missingFileEnvelope));

    const err = await uploadDocument(pdfFile()).catch((e: unknown) => e);

    expect(err).toBeInstanceOf(ApiError);
    const apiError = err as ApiError;
    expect(apiError.code).toBe("invalid_request");
    expect(apiError.details).toEqual({ field: "file" });
    expect(apiError.status).toBe(400);
  });
});

describe("classifyUpload", () => {
  it("classifies by id membership alone — status plays no part", () => {
    /* A re-uploaded book that is still processing is a legitimate duplicate:
       non-terminal status must not sway the classification. */
    const stillProcessing = {
      document: {
        ...uploadedDocument("book-known", "Known Book"),
        status: "extracting_items" as const,
      },
      ingestion: { status: "extracting_items" as const },
    };

    expect(classifyUpload(stillProcessing, new Set(["book-known"]))).toBe(
      "duplicate",
    );
    expect(classifyUpload(stillProcessing, new Set(["book-other"]))).toBe(
      "created",
    );
    expect(classifyUpload(stillProcessing, new Set())).toBe("created");
  });
});

/* ------------------------------------------------------------------ */
/* useUploadBooks — batch orchestration, 409 fallback, memoization.    */
/* ------------------------------------------------------------------ */

function renderUploadBooks() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  const wrapper = ({ children }: { children: ReactNode }) =>
    createElement(QueryClientProvider, { client: queryClient }, children);
  const { result } = renderHook(() => useUploadBooks(), { wrapper });
  return { queryClient, result };
}

interface SingleUploadStats {
  calls: number;
  maxInFlight: number;
  /** Handler-entry order — grows by one per request, strictly after exits. */
  entries: number[];
}

type SingleOutcome =
  | { kind: "created"; document: ReturnType<typeof uploadedDocument> }
  | { kind: "error"; status: number; envelope: typeof internalErrorEnvelope };

/**
 * Sequenced POST /documents handler: pops one scripted outcome per request,
 * tracking an in-flight counter — timestamps on sub-millisecond in-process
 * handlers are noise, so overlap is disproven by the counter never
 * exceeding 1 across the deliberate 10ms handler delay.
 */
function sequencedSingleUploadHandler(
  outcomes: SingleOutcome[],
  stats: SingleUploadStats,
) {
  let inFlight = 0;
  return http.post("/api/v1/documents", async () => {
    inFlight += 1;
    stats.calls += 1;
    stats.entries.push(stats.calls);
    stats.maxInFlight = Math.max(stats.maxInFlight, inFlight);
    await delay(10);
    const outcome = outcomes.shift();
    inFlight -= 1;
    if (!outcome) {
      return HttpResponse.json(internalErrorEnvelope, { status: 500 });
    }
    if (outcome.kind === "error") {
      return HttpResponse.json(outcome.envelope, { status: outcome.status });
    }
    return HttpResponse.json(
      { document: outcome.document, ingestion: { status: "queued" } },
      { status: 201 },
    );
  });
}

const emptyStats = (): SingleUploadStats => ({
  calls: 0,
  maxInFlight: 0,
  entries: [],
});

describe("useUploadBooks", () => {
  it("multi-file: posts one batch request with N parts under `files` and resolves the summary unchanged", async () => {
    const batchResponse: BatchUploadResponse = {
      items: [
        {
          filename: "one.pdf",
          status: "created",
          document_id: "doc-batch-1",
          error: null,
        },
        {
          filename: "two.pdf",
          status: "duplicate",
          document_id: "book-one-pan",
          error: null,
        },
        {
          filename: "three.txt",
          status: "error",
          document_id: null,
          error: "Only PDF uploads are supported.",
        },
      ],
      total: 3,
      created: 1,
      duplicates: 1,
      errors: 1,
    };
    let batchCalls = 0;
    let observed: ObservedUpload | null = null;
    server.use(
      documentsListHandler(libraryBookList),
      uploadBatchHandler(batchResponse, (o) => {
        batchCalls += 1;
        observed = o;
      }),
    );
    const { queryClient, result } = renderUploadBooks();

    const summary = await result.current.mutateAsync([
      pdfFile("one.pdf"),
      pdfFile("two.pdf"),
      pdfFile("three.txt"),
    ]);

    expect(summary).toEqual(batchResponse);
    expect(batchCalls).toBe(1);
    const seen = observed as unknown as ObservedUpload;
    expect(seen.filesPartCount).toBe(3);
    expect(seen.fieldNames).toContain("files");
    expect(seen.category).toBe("recipes");
    /* created or duplicate present → shelf invalidated. */
    await waitFor(() =>
      expect(queryClient.getQueryState(["documents"])?.isInvalidated).toBe(
        true,
      ),
    );
  });

  it("single file: classifies a content-hash hit as duplicate via the id snapshot", async () => {
    const existing = libraryBookDetails["book-one-pan"].document;
    server.use(
      documentsListHandler(libraryBookList),
      uploadDocumentHandler(existing),
    );
    const { queryClient, result } = renderUploadBooks();

    const summary = await result.current.mutateAsync([
      pdfFile("one-pan-again.pdf"),
    ]);

    expect(summary.items).toEqual([
      {
        filename: "one-pan-again.pdf",
        status: "duplicate",
        document_id: "book-one-pan",
        error: null,
        code: null,
        title: existing.title,
      },
    ]);
    expect(summary).toMatchObject({
      total: 1,
      created: 0,
      duplicates: 1,
      errors: 0,
    });
    await waitFor(() =>
      expect(queryClient.getQueryState(["documents"])?.isInvalidated).toBe(
        true,
      ),
    );
  });

  it("batch 409: falls back to strictly sequential singles with a unified summary", async () => {
    const stats = emptyStats();
    server.use(
      documentsListHandler(libraryBookList),
      uploadBatchErrorHandler(409, batchNotEnabledEnvelope),
      sequencedSingleUploadHandler(
        [
          {
            kind: "created",
            document: uploadedDocument("doc-f1", "Fresh One"),
          },
          {
            kind: "created",
            document: libraryBookDetails["book-one-pan"].document,
          },
          {
            kind: "error",
            status: 415,
            envelope: unsupportedFileTypeEnvelope,
          },
        ],
        stats,
      ),
    );
    const { result } = renderUploadBooks();

    const files = [
      pdfFile("fresh.pdf"),
      pdfFile("one-pan-again.pdf"),
      pdfFile("notes.txt"),
    ];
    const summary = await result.current.mutateAsync(files);

    expect(stats.calls).toBe(3);
    expect(stats.maxInFlight).toBe(1);
    expect(stats.entries).toEqual([1, 2, 3]);
    /* Client-side File.name survives — items map input order. */
    expect(summary.items.map((i) => i.filename)).toEqual([
      "fresh.pdf",
      "one-pan-again.pdf",
      "notes.txt",
    ]);
    expect(summary.items.map((i) => i.status)).toEqual([
      "created",
      "duplicate",
      "error",
    ]);
    expect(summary.items[2].error).toBe("Only PDF uploads are supported.");
    expect(summary.items[2].code).toBe("unsupported_file_type");
    expect(summary).toMatchObject({
      total: 3,
      created: 1,
      duplicates: 1,
      errors: 1,
    });
  });

  it("memoizes the 409 for the page load: a second multi-file drop issues no batch request", async () => {
    let batchCalls = 0;
    const stats = emptyStats();
    server.use(
      documentsListHandler(libraryBookList),
      uploadBatchErrorHandler(409, batchNotEnabledEnvelope, () => {
        batchCalls += 1;
      }),
      sequencedSingleUploadHandler(
        [
          { kind: "created", document: uploadedDocument("doc-m1", "Memo One") },
          { kind: "created", document: uploadedDocument("doc-m2", "Memo Two") },
          {
            kind: "created",
            document: uploadedDocument("doc-m3", "Memo Three"),
          },
          {
            kind: "created",
            document: uploadedDocument("doc-m4", "Memo Four"),
          },
        ],
        stats,
      ),
    );
    const { queryClient, result } = renderUploadBooks();

    await result.current.mutateAsync([pdfFile("a.pdf"), pdfFile("b.pdf")]);
    expect(batchCalls).toBe(1);
    expect(stats.calls).toBe(2);

    await result.current.mutateAsync([pdfFile("c.pdf"), pdfFile("d.pdf")]);
    expect(batchCalls).toBe(1);
    expect(stats.calls).toBe(4);

    /* The memo must survive GC — an observerless setQueryData entry with the
       default 5-minute gcTime would silently evict and re-probe. */
    const memo = queryClient
      .getQueryCache()
      .find({ queryKey: ["capabilities", "batch"] });
    expect(memo?.gcTime).toBe(Number.POSITIVE_INFINITY);
  });

  it("classifies the same file dropped twice in one cohort as created + duplicate", async () => {
    const stats = emptyStats();
    const sameDoc = uploadedDocument("doc-same", "Dropped Twice");
    server.use(
      documentsListHandler(libraryBookList),
      uploadBatchErrorHandler(409, batchNotEnabledEnvelope),
      sequencedSingleUploadHandler(
        [
          { kind: "created", document: sameDoc },
          /* Content-hash hit: the backend returns the SAME document again. */
          { kind: "created", document: sameDoc },
        ],
        stats,
      ),
    );
    const { result } = renderUploadBooks();

    const summary = await result.current.mutateAsync([
      pdfFile("same.pdf"),
      pdfFile("same.pdf"),
    ]);

    expect(summary.items.map((i) => i.status)).toEqual([
      "created",
      "duplicate",
    ]);
    expect(summary).toMatchObject({ created: 1, duplicates: 1, errors: 0 });
  });

  it("surfaces a batch 500 as ApiError without any fallback attempt", async () => {
    const stats = emptyStats();
    server.use(
      documentsListHandler(libraryBookList),
      uploadBatchErrorHandler(500, internalErrorEnvelope),
      sequencedSingleUploadHandler([], stats),
    );
    const { result } = renderUploadBooks();

    const err = await result.current
      .mutateAsync([pdfFile("a.pdf"), pdfFile("b.pdf")])
      .catch((e: unknown) => e);

    expect(err).toBeInstanceOf(ApiError);
    expect((err as ApiError).status).toBe(500);
    expect(stats.calls).toBe(0);
  });

  it("leaves ['documents'] uninvalidated when nothing was created or duplicate", async () => {
    server.use(
      documentsListHandler(libraryBookList),
      uploadErrorHandler(415, unsupportedFileTypeEnvelope),
    );
    const { queryClient, result } = renderUploadBooks();

    const summary = await result.current.mutateAsync([pdfFile("notes.txt")]);

    expect(summary).toMatchObject({ created: 0, duplicates: 0, errors: 1 });
    expect(summary.items[0].code).toBe("unsupported_file_type");
    expect(queryClient.getQueryState(["documents"])?.isInvalidated).toBe(false);
  });

  /* A response lost AFTER the server committed the document (review #1).
     The client cannot distinguish "never arrived" from "never happened", so
     both paths must reconcile the shelf instead of asserting failure. */
  it("single path: a lost response marks the item indeterminate and reconciles the shelf", async () => {
    server.use(
      documentsListHandler(libraryBookList),
      http.post("/api/v1/documents", () => HttpResponse.error()),
    );
    const { queryClient, result } = renderUploadBooks();

    const summary = await result.current.mutateAsync([pdfFile("lost.pdf")]);

    expect(summary).toMatchObject({ created: 0, duplicates: 0, errors: 1 });
    expect(summary.items[0].indeterminate).toBe(true);
    expect(summary.items[0].code).toBe("network_error");
    await waitFor(() =>
      expect(queryClient.getQueryState(["documents"])?.isInvalidated).toBe(
        true,
      ),
    );
  });

  it("single path: a 5xx is indeterminate, a definitive 4xx is not", async () => {
    server.use(
      documentsListHandler(libraryBookList),
      uploadErrorHandler(500, internalErrorEnvelope),
    );
    const { queryClient, result } = renderUploadBooks();

    const summary = await result.current.mutateAsync([pdfFile("boom.pdf")]);

    expect(summary.items[0].indeterminate).toBe(true);
    await waitFor(() =>
      expect(queryClient.getQueryState(["documents"])?.isInvalidated).toBe(
        true,
      ),
    );
  });

  it("batch path: a rejected cohort still reconciles the shelf", async () => {
    const stats = emptyStats();
    server.use(
      documentsListHandler(libraryBookList),
      uploadBatchErrorHandler(500, internalErrorEnvelope),
      sequencedSingleUploadHandler([], stats),
    );
    const { queryClient, result } = renderUploadBooks();

    await result.current
      .mutateAsync([pdfFile("a.pdf"), pdfFile("b.pdf")])
      .catch(() => undefined);

    /* No fallback — but the cohort may have partly committed before the 500. */
    expect(stats.calls).toBe(0);
    await waitFor(() =>
      expect(queryClient.getQueryState(["documents"])?.isInvalidated).toBe(
        true,
      ),
    );
  });

  it("degrades to the cached snapshot when the pre-upload list refresh fails", async () => {
    server.use(
      http.get("/api/v1/documents", () =>
        HttpResponse.json(internalErrorEnvelope, { status: 500 }),
      ),
      uploadDocumentHandler(libraryBookDetails["book-one-pan"].document),
    );
    const { queryClient, result } = renderUploadBooks();
    /* A previous shelf visit populated the cache. */
    queryClient.setQueryData(["documents"], { documents: libraryBookList });

    const summary = await result.current.mutateAsync([
      pdfFile("one-pan-again.pdf"),
    ]);

    expect(summary.items[0].status).toBe("duplicate");
  });
});
