import { ApiError } from "../../src/api";
import { classifyUpload, uploadDocument } from "../../src/api/uploads";
import {
  missingFileEnvelope,
  type ObservedUpload,
  unsupportedFileTypeEnvelope,
  uploadDocumentHandler,
  uploadErrorHandler,
  uploadedDocument,
} from "../msw/handlers";
import { server } from "../msw/server";

/* jsdom multipart limit (see handlers.ts): assertions below stick to field
   names, part counts and scalar values — never filenames or file bytes. */

const pdfFile = (name = "book.pdf") =>
  new File([new Uint8Array([0x25, 0x50, 0x44, 0x46, 0x2d])], name, {
    type: "application/pdf",
  });

describe("uploadDocument", () => {
  it("posts multipart with file + category=recipes and resolves the response", async () => {
    const document = uploadedDocument("book-new", "A Brand New Book");
    let observed: ObservedUpload | null = null;
    server.use(uploadDocumentHandler(document, (o) => (observed = o)));

    const response = await uploadDocument(pdfFile());

    expect(response.document.id).toBe("book-new");
    expect(response.ingestion.status).toBe("queued");
    expect(observed).not.toBeNull();
    const seen = observed as unknown as ObservedUpload;
    expect(seen.fieldNames).toEqual(["file", "category"]);
    expect(seen.category).toBe("recipes");
    /* Positive assertion — "no JSON content-type" would also pass if the
       header were missing for the wrong reason. Boundary is generated by
       the fetch implementation under jsdom; "browser-set" is only
       demonstrable live. */
    expect(seen.contentType).toMatch(/^multipart\/form-data; boundary=/);
  });

  it("rejects a 415 with the typed unsupported_file_type ApiError", async () => {
    server.use(uploadErrorHandler(415, unsupportedFileTypeEnvelope));

    const err = await uploadDocument(pdfFile("pretending.txt")).catch(
      (e: unknown) => e,
    );

    expect(err).toBeInstanceOf(ApiError);
    const apiError = err as ApiError;
    expect(apiError.code).toBe("unsupported_file_type");
    expect(apiError.message).toBe("Only PDF uploads are supported.");
    expect(apiError.details).toEqual({ expected: "application/pdf" });
    expect(apiError.status).toBe(415);
  });

  it("rejects a 400 with the typed invalid_request ApiError", async () => {
    server.use(uploadErrorHandler(400, missingFileEnvelope));

    const err = await uploadDocument(pdfFile()).catch((e: unknown) => e);

    expect(err).toBeInstanceOf(ApiError);
    const apiError = err as ApiError;
    expect(apiError.code).toBe("invalid_request");
    expect(apiError.details).toEqual({ field: "file" });
    expect(apiError.status).toBe(400);
  });
});

describe("classifyUpload", () => {
  it("classifies by id membership alone — status plays no part", () => {
    /* A re-uploaded book that is still processing is a legitimate duplicate:
       non-terminal status must not sway the classification. */
    const stillProcessing = {
      document: {
        ...uploadedDocument("book-known", "Known Book"),
        status: "extracting_items" as const,
      },
      ingestion: { status: "extracting_items" as const },
    };

    expect(classifyUpload(stillProcessing, new Set(["book-known"]))).toBe(
      "duplicate",
    );
    expect(classifyUpload(stillProcessing, new Set(["book-other"]))).toBe(
      "created",
    );
    expect(classifyUpload(stillProcessing, new Set())).toBe("created");
  });
});
