/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Documents Batch
         * @description Upload a cohort of PDFs and defer extraction into the Anthropic batch path.
         *
         *     Each file is created exactly as ``POST /documents`` does (shared helper), but
         *     enqueued with ``batch_mode=True`` so ``process_document`` registers windows
         *     instead of running synchronous extraction. Per-file failures (non-PDF, etc.)
         *     yield an ``error`` item without aborting the cohort.
         *
         *     **Refuses creation unless the Anthropic batch path is enabled** (``llm_provider
         *     == "anthropic"`` + a key): otherwise the created docs would register windows
         *     that no submitter could ever drain, stranding them in ``EXTRACTING_ITEMS``
         *     (DECISIONS #3; Codex round-1 #2).
         */
        post: operations["upload_documents_batch_api_v1_documents_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete a document and everything derived from it (Phase 21.2).
         *
         *     ``SELECT ... FOR UPDATE`` on the document row serializes this handler
         *     against ``transition_to`` (same lock) and the reprocess route's guarded
         *     UPDATE, so a document cannot slip from terminal to ``queued`` between the
         *     terminal check and the cascade (D3). Non-terminal documents 409 with the
         *     same ``ingestion_already_running`` envelope the reprocess guard uses.
         *
         *     The stored PDF is removed only *after* the commit, best-effort (D6): the
         *     DB is the source of truth, and a file deleted before a rolled-back commit
         *     would strand a live document pointing at a missing PDF — strictly worse
         *     than an orphaned file. On storage failure the key is logged (ERROR) and
         *     the 204 stands. 204 carries no body (D7), so the per-table deleted-row
         *     counts are logged at INFO as the operation's only audit trail (D5).
         */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Status
         * @description Report ingestion progress for a document.
         *
         *     Deliberately exempt from Phase 21.3's read-time review derivation (plan
         *     D3): this endpoint reports pipeline/ingestion truth (progress, terminal,
         *     failure); the review pill reads list/detail.
         *
         *     For a non-terminal doc the in-flight version is the highest existing span
         *     version (Epic 11.2, DECISIONS #5) — ``max + 1`` work for a new_source_version
         *     run already shows up as v(new) spans, while initial ingestion / a reuse run
         *     stays on the current version; it defaults to ``1`` before any span exists.
         *     Progress is suppressed only when the in-flight version equals the *already
         *     active* version — a reuse reprocess re-runs over existing spans without
         *     creating new ones, so the surviving spans are not this run's progress. A
         *     new_source_version run (in-flight > active) and initial ingestion (no active
         *     version) both report the in-flight version's spans. Terminal docs report their
         *     active version's final counts (a failed doc with active=null gets (0, None)).
         */
        get: operations["get_document_status_api_v1_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Document */
        post: operations["reprocess_document_api_v1_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Documents */
        post: operations["search_documents_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_v1_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compose Menu */
        post: operations["compose_menu_api_v1_menus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Knowledge Item
         * @description Write a recipe by hand, with no PDF and no extraction behind it.
         *
         *     The one way a knowledge item enters this system without an ingest run. It
         *     lands on the shared **handwritten shelf** — a single Document that
         *     ``ensure_manual_shelf`` creates on first use and every manual recipe
         *     thereafter shares (see ``ingestion/manual`` for why the FKs demand a source
         *     chain at all, and why there is one rather than one per recipe).
         *
         *     **Straight to the shelf, never to the queue.** The item is born ``indexing``
         *     and an ``index_knowledge_item`` job chunks, embeds and flips it to ``ready``
         *     — the approve path's second half, reached without the first, because there
         *     is no extraction to second-guess. Soft-validation warnings are still derived
         *     and stored (``authored_recipe``), they just do not gate the status: a typed
         *     recipe with no method carries ``no_steps`` for a later edit to clear,
         *     without being held back from search over it.
         *
         *     Two consequences of that, both shared with approve and with editing a
         *     shelved item. The recipe is **absent from search until the worker
         *     finishes**, which is the price of not blocking the request on an embedding
         *     round-trip — the 201 says ``indexing`` and means it. And if the job exhausts
         *     its retries, ``sweep_stuck_jobs``' item-level pass returns the row to
         *     ``needs_review``, which is honest: the row genuinely has no chunks, and that
         *     is exactly what ``needs_review`` means.
         *
         *     The DB commit and the Redis enqueue are not one transaction. On an enqueue
         *     failure the compensation **deletes the row** rather than parking it in the
         *     review queue the way approve and edit do — their compensation returns an
         *     item to a state it came from, while here there is no earlier state to return
         *     to. A 500 that also left a half-created recipe behind would make the obvious
         *     retry a duplicate. If the delete itself fails, the stuck-indexing sweep
         *     still rescues the row into ``needs_review``, so nothing is unrecoverable.
         */
        post: operations["create_knowledge_item_api_v1_knowledge_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Item */
        get: operations["get_knowledge_item_api_v1_knowledge_items__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Knowledge Item
         * @description Delete one recipe and everything derived from it.
         *
         *     The per-item counterpart to ``DELETE /documents/{document_id}``, and the
         *     same shape: 404 unknown → 409 mid-reprocess → cascade → commit → log the
         *     per-table counts (a body-less 204 leaves no other audit trail).
         *
         *     ``SELECT ... FOR UPDATE`` takes the **document** row, not the item — the
         *     lock order every writer here uses (``jobs.py``: document first, item
         *     second), and inverting it risks a deadlock against a concurrent reprocess.
         *     It also does the real work: it serializes this handler against
         *     ``index_knowledge_item``, so deleting an item that is mid-``indexing`` is
         *     safe without any new machinery — the job either has not started (and then
         *     finds the item gone, hitting its ``item is None`` no-op) or has finished.
         *
         *     Allowed at any item status, ``ready`` included. That is the point: a
         *     shelved recipe had no removal path at all, and ``rejected`` — the soft
         *     delete the review surface offers — reaches only ``needs_review`` items.
         *
         *     Not closed here: deleting the last ``ready`` item of the active generation
         *     leaves ``documents.active_source_version`` pointing at a generation with
         *     nothing in it. Not corrupt — search simply finds nothing and the counts
         *     read zero — and reprocessing is the existing way back.
         */
        delete: operations["delete_knowledge_item_api_v1_knowledge_items__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Knowledge Item
         * @description Correct a knowledge item in place (Epic 22.2; ``ready`` items since).
         *
         *     Content warnings are re-derived from the corrected text either way — so a
         *     reviewer who fixes "no ingredients" stops seeing the flag that said so,
         *     while ``low_overall_confidence`` / ``low_boundary_confidence`` survive,
         *     because retyping a line does not attest that the recipe was cut out of the
         *     page correctly.
         *
         *     Two statuses, two very different transactions:
         *
         *     - ``needs_review`` — the original path, and still a pure row rewrite.
         *       Editing never decides: the item is *still* ``needs_review`` afterwards,
         *       and the edited text is what gets chunked when the reviewer approves.
         *       These items have no chunks and no embeddings, so there is nothing else to
         *       keep in step.
         *     - ``ready`` — the item is indexed, so a row rewrite alone would leave
         *       ``chunks`` and ``chunk_embeddings`` describing the *old* text and the
         *       recipe findable by words it no longer contains. The handler therefore
         *       drops its index rows in the same transaction, flips it to ``indexing``,
         *       and enqueues ``index_knowledge_item`` to rebuild and re-embed from the
         *       saved text — the delete-and-re-embed path this docstring used to say did
         *       not exist.
         *
         *     Two consequences of the ``ready`` path, both deliberate. The recipe is
         *     **absent from search until the worker finishes** (search requires chunks),
         *     which is the price of not blocking the request on an embedding round-trip.
         *     And if the job exhausts its retries, the item-level pass in
         *     ``sweep_stuck_jobs`` returns the row to ``needs_review`` — an edit can
         *     therefore demote a shelved recipe into the review queue. That is honest
         *     rather than lossy: the row genuinely has no chunks at that point, which is
         *     exactly what ``needs_review`` means.
         *
         *     Guards run in the same order as ``POST …/review`` so each stays reachable
         *     rather than masked: 404 unknown id → 409 mid-reprocess document → 409 stale
         *     generation → guarded UPDATE → 404 not editable. The empty-body 400 sits
         *     *after* the 404 so an unknown id reports as unknown whatever the body says.
         *
         *     Not closed here (and not asked for by the epic): two concurrent PATCHes are
         *     last-write-wins on content. The guarded UPDATE closes the edit-vs-decide
         *     race, and the COALESCE keeps the snapshot at the original extraction, but
         *     neither is a content-level precondition — two reviewers editing the same
         *     item in two tabs would see the second edit replace the first wholesale.
         */
        patch: operations["update_knowledge_item_api_v1_knowledge_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/documents/{document_id}/knowledge-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Knowledge Items
         * @description List one book's knowledge items, newest first.
         *
         *     The listing ``GET /review-items`` cannot be: it answers for *every* status,
         *     which is what makes a book browsable once its recipes are on the shelf.
         *
         *     Unfiltered, it hides ``superseded`` and ``rejected`` rows — a dead
         *     generation and a thrown-away item are not part of the book's contents — but
         *     an explicit ``?status=`` reaches either, so nothing is unreachable. Unlike
         *     ``/review-items``, the document is *addressed* rather than filtered, so an
         *     unknown id is a 404 (the ``GET /documents/{id}`` rule), not an empty list.
         *
         *     There is deliberately no document-status guard: unlike the review queue,
         *     which excludes mid-reprocess books because deciding their items is unsafe,
         *     reading a book's contents while it reprocesses is harmless. The write verbs
         *     keep their own 409.
         */
        get: operations["list_document_knowledge_items_api_v1_documents__document_id__knowledge_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items/{item_id}/favourite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add Favourite
         * @description Star a recipe. 200 with the star's timestamp, whether or not it is new.
         *
         *     ``ON CONFLICT DO NOTHING`` plus a read-back, rather than an upsert that
         *     restamps ``created_at``: the second PUT of a double-click must not reorder
         *     the favourites list. The read-back is also what makes the timestamp in the
         *     response the *server's* — a concurrent PUT that won the insert produced it.
         *
         *     PUT rather than POST because that is what this is: an idempotent write of a
         *     named sub-resource whose whole content is "it exists".
         */
        put: operations["add_favourite_api_v1_knowledge_items__item_id__favourite_put"];
        post?: never;
        /**
         * Remove Favourite
         * @description Unstar a recipe. 204 whether or not it was starred.
         *
         *     Deliberately NOT a 404 on an unstarred recipe: the caller asked for a state
         *     ("this is not favourited") that holds when the handler returns, and a UI
         *     retrying a dropped request would otherwise be told its own success failed.
         *     An unknown *item* is still a 404 — that is a caller mistake, not a repeat.
         *
         *     Nothing is logged: unlike the item delete this destroys no content, and the
         *     row can be recreated with one click.
         */
        delete: operations["remove_favourite_api_v1_knowledge_items__item_id__favourite_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Favourites
         * @description Every starred recipe, newest star first.
         *
         *     The same ``limit``/``offset``, the same bounds and the same no-total,
         *     no-cursor contract as the shelf and the review queue: clients walk pages
         *     until one comes back short.
         *
         *     Ordered by the STAR's ``created_at``, not the item's — "what I saved most
         *     recently" is the question this surface answers, and the two orders diverge
         *     the moment an old recipe is starred. ``knowledge_item_id`` breaks ties so
         *     the page walk cannot repeat or skip a row when two stars share a timestamp.
         */
        get: operations["list_favourites_api_v1_favourites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Review Items
         * @description List pending-review knowledge items, newest first (contract §1, D4).
         *
         *     Every ``needs_review`` item of a terminal document — including a
         *     ``failed`` one (D9 recorded consequence) and every live generation of a
         *     twice-reviewed document (D9: staleness is handled at decision time, not by
         *     hiding rows here). Unknown ``document_id`` → naturally 200 + empty list.
         */
        get: operations["list_review_items_api_v1_review_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Knowledge Item
         * @description Decide a pending-review item (contract §2, plan D1/D6/D9).
         *
         *     Approve flips ``needs_review → indexing`` and enqueues
         *     ``index_knowledge_item``; reject flips to terminal ``rejected``. The two
         *     409 guards run first (advisory read-then-act); the atomic guarded UPDATE
         *     is what actually closes the decide/decide race.
         *
         *     The DB commit and the Redis enqueue are *not* one transaction — the
         *     enqueue-failure revert is best-effort compensation, not atomicity (D1).
         *     The reachable end states are: decided-and-enqueued; reverted to
         *     ``needs_review`` (compensating UPDATE, user re-approves); or a stuck
         *     ``indexing`` row that the item-level sweep returns to ``needs_review``.
         *     Either way indexing completes or the item returns to the queue.
         */
        post: operations["review_knowledge_item_api_v1_knowledge_items__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerBody */
        AnswerBody: {
            /** Style */
            style: string;
            /** Text */
            text: string;
            /** Citations */
            citations: string[];
        };
        /** AnswerCitation */
        AnswerCitation: {
            /** Citation Id */
            citation_id: string;
            /** Knowledge Item Id */
            knowledge_item_id: string;
            /** Source Span Id */
            source_span_id: string;
            /** Label */
            label: string;
        };
        /**
         * AnswerDebugInfo
         * @description Dev-only answer diagnostics (doc 8 § 11), gated like the search debug payload.
         */
        AnswerDebugInfo: {
            /** Retrieval Mode */
            retrieval_mode: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Context Item Count */
            context_item_count: number;
            /** Citation Count */
            citation_count: number;
            retrieval_debug?: components["schemas"]["RetrievalDebugInfo"] | null;
        };
        /** AnswerOptions */
        AnswerOptions: {
            /**
             * Style
             * @default recommendation
             */
            style: string;
            /**
             * Include Results
             * @default false
             */
            include_results: boolean;
            /**
             * Include Debug
             * @default false
             */
            include_debug: boolean;
        };
        /** AnswerRequestBody */
        AnswerRequestBody: {
            /** Query */
            query: string;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /**
             * @default {
             *       "item_type": "recipe",
             *       "document_ids": [],
             *       "exclude_needs_review": true
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /**
             * @default {
             *       "mode": "hybrid"
             *     }
             */
            retrieval: components["schemas"]["AnswerRetrievalOptions"];
            /**
             * @default {
             *       "style": "recommendation",
             *       "include_results": false,
             *       "include_debug": false
             *     }
             */
            answer: components["schemas"]["AnswerOptions"];
        };
        /** AnswerResponse */
        AnswerResponse: {
            /** Query */
            query: string;
            answer: components["schemas"]["AnswerBody"];
            /**
             * Recommendations
             * @default []
             */
            recommendations: components["schemas"]["Recommendation"][];
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["AnswerCitation"][];
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["KnowledgeItemResult"][];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            debug?: components["schemas"]["AnswerDebugInfo"] | null;
        };
        /** AnswerRetrievalOptions */
        AnswerRetrievalOptions: {
            /**
             * Mode
             * @default hybrid
             */
            mode: string;
            /** Limit */
            limit?: number | null;
        };
        /**
         * BatchUploadErrorCode
         * @description Machine-readable code on ``error`` items (Epic 21.1, D2).
         *
         *     Mirrors the ``ErrorCode`` values actually raisable by the per-file upload
         *     helper; anything unexpected maps to ``internal_error``.
         * @enum {string}
         */
        BatchUploadErrorCode: "invalid_request" | "unsupported_file_type" | "internal_error";
        /**
         * BatchUploadItemResult
         * @description Per-file outcome in a batch cohort upload (Epic 19.2).
         */
        BatchUploadItemResult: {
            /** Filename */
            filename: string;
            status: components["schemas"]["BatchUploadItemStatus"];
            /** Document Id */
            document_id?: string | null;
            /** Error */
            error?: string | null;
            error_code?: components["schemas"]["BatchUploadErrorCode"] | null;
        };
        /**
         * BatchUploadItemStatus
         * @description Per-file outcome of a batch cohort upload — closed set (Epic 21.1).
         * @enum {string}
         */
        BatchUploadItemStatus: "created" | "duplicate" | "error";
        /** BatchUploadResponse */
        BatchUploadResponse: {
            /** Items */
            items: components["schemas"]["BatchUploadItemResult"][];
            /** Total */
            total: number;
            /** Created */
            created: number;
            /** Duplicates */
            duplicates: number;
            /** Errors */
            errors: number;
        };
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** File */
            file?: string | null;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /** Title */
            title?: string | null;
            /** Author */
            author?: string | null;
            /** Language */
            language?: string | null;
        };
        /** Body_upload_documents_batch_api_v1_documents_batch_post */
        Body_upload_documents_batch_api_v1_documents_batch_post: {
            /** Files */
            files: string[];
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /** Language */
            language?: string | null;
        };
        /**
         * CourseSelection
         * @description The one recipe chosen for a course. ``title`` is rebuilt from the pack.
         */
        CourseSelection: {
            /** Knowledge Item Id */
            knowledge_item_id: string;
            /** Title */
            title: string;
            /** Reason */
            reason: string;
            /** Citation Ids */
            citation_ids: string[];
        };
        /** DisplayProjection */
        DisplayProjection: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            /** Snippet */
            snippet: string | null;
            /** Badges */
            badges: string[];
        };
        /** DocumentCounts */
        DocumentCounts: {
            /** Source Spans */
            source_spans: number;
            /** Knowledge Items */
            knowledge_items: number;
            /** Ready Items */
            ready_items: number;
            /** Needs Review Items */
            needs_review_items: number;
            /** Chunks */
            chunks: number;
        };
        /** DocumentDetailResponse */
        DocumentDetailResponse: {
            document: components["schemas"]["DocumentResponse"];
            counts: components["schemas"]["DocumentCounts"];
        };
        /**
         * DocumentListItem
         * @description The doc §3 list item — smaller than ``DocumentResponse`` (no
         *     ``asset_id``/``language``/timestamps).
         */
        DocumentListItem: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Subcategory */
            subcategory: string | null;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
            /** Active Source Version */
            active_source_version: number | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentListItem"][];
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Id */
            id: string;
            /** Asset Id */
            asset_id: string;
            /** Category */
            category: string;
            /** Subcategory */
            subcategory: string | null;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Source Type */
            source_type: string;
            /** Language */
            language: string | null;
            /** Active Source Version */
            active_source_version: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Favourite */
        Favourite: {
            /** Knowledge Item Id */
            knowledge_item_id: string;
            /**
             * Favourited At
             * Format: date-time
             */
            favourited_at: string;
        };
        /** FavouriteResponse */
        FavouriteResponse: {
            favourite: components["schemas"]["Favourite"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * IngestionFailureInfo
         * @description Latest ingestion failure for a FAILED document (doc 6 § 5; Epic 21 D1).
         *
         *     ``stage`` is the status the document failed *from*
         *     (``IngestionFailure.last_status``), not its current status.
         *     ``error_message`` is deliberately excluded — ``reason`` is the stable,
         *     FE-presentable code.
         */
        IngestionFailureInfo: {
            /** Reason */
            reason: string;
            /** Stage */
            stage: string;
            /**
             * Failed At
             * Format: date-time
             */
            failed_at: string;
        };
        /** IngestionProgress */
        IngestionProgress: {
            /** Stage */
            stage: string;
            /** Message */
            message: string | null;
            /** Pages Total */
            pages_total: number | null;
            /** Pages Processed */
            pages_processed: number | null;
        };
        /** IngestionStatusResponse */
        IngestionStatusResponse: {
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Active Source Version */
            active_source_version: number | null;
            /** Current Source Version */
            current_source_version: number | null;
            progress: components["schemas"]["IngestionProgress"];
            /** Terminal */
            terminal: boolean;
            failure?: components["schemas"]["IngestionFailureInfo"] | null;
        };
        /**
         * KnowledgeItemCreateRequest
         * @description A recipe a human typed rather than one an extractor found.
         *
         *     The create-side twin of ``KnowledgeItemUpdateRequest``, with deliberately
         *     the same field set and the same rules — a recipe you can author is exactly
         *     a recipe you can correct, and a field that appears here but not there would
         *     be one nobody could ever fix.
         *
         *     Two differences, both forced by there being no existing row:
         *
         *     - ``title`` is required, not optional. Absent means nothing to leave alone.
         *     - the two lists default to empty rather than to absent. Whole-array
         *       replacement has no "unchanged" to express on a row that does not exist
         *       yet, so an omitted list is an empty section.
         *
         *     Same exclusions as the update request, for the same reason: ``confidence``,
         *     ``source_span_ids``, ``schema``, ``item_type`` and ``warnings`` are
         *     machine-owned provenance. Here the machine that owns them is
         *     ``ingestion/manual.authored_recipe``, which derives every one of them from
         *     the text below.
         *
         *     Note what is NOT required: a recipe with no ingredients and no steps is
         *     accepted, because ``PATCH`` accepts emptying both and a create rule the edit
         *     rule does not share would just be a trap on the way in.
         */
        KnowledgeItemCreateRequest: {
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Yield */
            yield?: string | null;
            /** Prep Time */
            prep_time?: string | null;
            /** Cook Time */
            cook_time?: string | null;
            /** Total Time */
            total_time?: string | null;
            /** Ingredients */
            ingredients?: string[];
            /** Steps */
            steps?: string[];
        };
        /** KnowledgeItemDetail */
        KnowledgeItemDetail: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Item Type */
            item_type: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Status */
            status: string;
            /** Source Span Ids */
            source_span_ids: string[];
            /** Confidence */
            confidence: {
                [key: string]: unknown;
            } | null;
            /** Structured Data */
            structured_data: {
                [key: string]: unknown;
            };
            /**
             * Review Reasons
             * @default []
             */
            review_reasons: components["schemas"]["ReviewReason"][];
            review_thresholds?: components["schemas"]["ReviewThresholds"] | null;
            /** Edited At */
            edited_at?: string | null;
            /** Favourited At */
            favourited_at?: string | null;
        };
        /** KnowledgeItemDisplay */
        KnowledgeItemDisplay: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
        };
        /**
         * KnowledgeItemListResponse
         * @description ``GET /documents/{document_id}/knowledge-items``.
         *
         *     No total and no cursor, matching ``ReviewItemListResponse`` — clients walk
         *     ``limit``/``offset`` until a page comes back short.
         */
        KnowledgeItemListResponse: {
            /** Knowledge Items */
            knowledge_items: components["schemas"]["ReviewItem"][];
        };
        /** KnowledgeItemResponse */
        KnowledgeItemResponse: {
            knowledge_item: components["schemas"]["KnowledgeItemDetail"];
            display: components["schemas"]["KnowledgeItemDisplay"];
            /** Source Citations */
            source_citations: components["schemas"]["KnowledgeItemSourceCitation"][];
        };
        /** KnowledgeItemResult */
        KnowledgeItemResult: {
            /**
             * Type
             * @default knowledge_item_result
             * @constant
             */
            type: "knowledge_item_result";
            item: components["schemas"]["ResultItem"];
            display: components["schemas"]["DisplayProjection"];
            structured_preview: components["schemas"]["StructuredPreview"];
            document: components["schemas"]["ResultDocument"];
            /** Matched Chunks */
            matched_chunks: components["schemas"]["MatchedChunk"][];
            /** Source Citations */
            source_citations: components["schemas"]["SourceCitation"][];
        };
        /** KnowledgeItemSourceCitation */
        KnowledgeItemSourceCitation: {
            /** Source Span Id */
            source_span_id: string;
            /** Label */
            label: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * KnowledgeItemUpdateRequest
         * @description A reviewer's in-place correction of a ``needs_review`` item (Epic 22.2).
         *
         *     Every field is optional and read with ``exclude_unset`` semantics: absent
         *     means "leave it alone", explicit ``null`` means "clear it". Clearing a
         *     summary or a yield is a real operation, so the two cannot be conflated.
         *
         *     The two lists are **whole-array replacement** — what a form submits — which
         *     is what makes add, remove and reorder fall out for free.
         *
         *     Only the fields a human can meaningfully author are here. ``confidence``,
         *     ``source_span_ids``, ``schema``, ``item_type`` and ``warnings`` are
         *     machine-owned provenance and are not client-writable; the per-ingredient
         *     parse (``quantity_value``, ``unit_normalized``, …) is nulled on an edited
         *     line rather than maintained by hand.
         */
        KnowledgeItemUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Yield */
            yield?: string | null;
            /** Prep Time */
            prep_time?: string | null;
            /** Cook Time */
            cook_time?: string | null;
            /** Total Time */
            total_time?: string | null;
            /** Ingredients */
            ingredients?: string[] | null;
            /** Steps */
            steps?: string[] | null;
        };
        /** MatchedChunk */
        MatchedChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Chunk Type */
            chunk_type: string;
            /** Score */
            score: number;
        };
        /**
         * MenuBody
         * @description The menu as a whole: its name, the coherence argument, and its citations.
         */
        MenuBody: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Citations */
            citations: string[];
        };
        /**
         * MenuCourse
         * @description One course: what was planned, what was retrieved, and what was chosen.
         *
         *     ``selection`` is ``null`` when the course could not be filled — retrieval
         *     returned nothing for its query, or the fallback path had no candidate to pick.
         *     A course is never dropped from the response for being unfillable: the caller
         *     asked for it, so it is reported empty rather than silently omitted.
         */
        MenuCourse: {
            /** Slot */
            slot: string;
            /** Query */
            query: string;
            /**
             * Note
             * @default
             */
            note: string;
            selection?: components["schemas"]["CourseSelection"] | null;
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["KnowledgeItemResult"][];
        };
        /**
         * MenuDebugInfo
         * @description Dev-only menu diagnostics, gated exactly like the search/answer debug blocks.
         */
        MenuDebugInfo: {
            /** Retrieval Mode */
            retrieval_mode: string;
            /** Model */
            model: string;
            /** Plan Prompt Version */
            plan_prompt_version: string;
            /** Selection Prompt Version */
            selection_prompt_version: string;
            /** Plan Is Fallback */
            plan_is_fallback: boolean;
            /** Course Count */
            course_count: number;
            /** Candidate Count */
            candidate_count: number;
            /** Context Item Count */
            context_item_count: number;
            /** Citation Count */
            citation_count: number;
            /** Retrieval Debug By Slot */
            retrieval_debug_by_slot?: {
                [key: string]: components["schemas"]["RetrievalDebugInfo"];
            } | null;
        };
        /** MenuOptions */
        MenuOptions: {
            /**
             * Include Candidates
             * @default false
             */
            include_candidates: boolean;
            /**
             * Include Debug
             * @default false
             */
            include_debug: boolean;
            /** Max Courses */
            max_courses?: number | null;
        };
        /** MenuRequestBody */
        MenuRequestBody: {
            /** Query */
            query: string;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /**
             * @default {
             *       "item_type": "recipe",
             *       "document_ids": [],
             *       "exclude_needs_review": true
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /**
             * @default {
             *       "mode": "hybrid"
             *     }
             */
            retrieval: components["schemas"]["MenuRetrievalOptions"];
            /**
             * @default {
             *       "include_candidates": false,
             *       "include_debug": false
             *     }
             */
            menu: components["schemas"]["MenuOptions"];
        };
        /** MenuResponse */
        MenuResponse: {
            /** Query */
            query: string;
            /**
             * Theme
             * @default
             */
            theme: string;
            menu: components["schemas"]["MenuBody"];
            /**
             * Courses
             * @default []
             */
            courses: components["schemas"]["MenuCourse"][];
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["AnswerCitation"][];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            debug?: components["schemas"]["MenuDebugInfo"] | null;
        };
        /** MenuRetrievalOptions */
        MenuRetrievalOptions: {
            /**
             * Mode
             * @default hybrid
             */
            mode: string;
            /** Candidates Per Course */
            candidates_per_course?: number | null;
        };
        /** Recommendation */
        Recommendation: {
            /** Knowledge Item Id */
            knowledge_item_id: string;
            /** Title */
            title: string;
            /** Reason */
            reason: string;
            /** Citation Ids */
            citation_ids: string[];
        };
        /** ReprocessRequest */
        ReprocessRequest: {
            /** Mode */
            mode: string;
            /** Reason */
            reason?: string | null;
        };
        /** ReprocessResponse */
        ReprocessResponse: {
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
            /** Previous Active Source Version */
            previous_active_source_version: number | null;
            /** Current Source Version */
            current_source_version: number | null;
        };
        /** ResultDocument */
        ResultDocument: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
        };
        /** ResultItem */
        ResultItem: {
            /** Id */
            id: string;
            /** Item Type */
            item_type: string;
            /** Schema */
            schema: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Status */
            status: string;
            /** Confidence */
            confidence: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RetrievalDebugInfo
         * @description Loose projection of the Epic 12 debug payload (doc 7 § 12).
         *
         *     Modeled permissively so doc-7 evolution does not break the schema.
         */
        RetrievalDebugInfo: {
            /** Retrieval Mode */
            retrieval_mode: string;
            /** Normalized Query */
            normalized_query: string;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Keyword Top K */
            keyword_top_k?: number | null;
            /** Vector Top K */
            vector_top_k?: number | null;
            /** Keyword Candidates */
            keyword_candidates?: number | null;
            /** Vector Candidates */
            vector_candidates?: number | null;
            /** Merged Candidates */
            merged_candidates?: number | null;
            /** Grouped Items */
            grouped_items?: number | null;
            /** Rerank Applied */
            rerank_applied?: boolean | null;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "approved" | "rejected";
        /** ReviewItem */
        ReviewItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Item Type */
            item_type: string;
            /** Status */
            status: string;
            document: components["schemas"]["ReviewItemDocument"];
            source_pages: components["schemas"]["ReviewItemSourcePages"];
            extraction: components["schemas"]["ReviewItemExtraction"];
            /** Flags */
            flags: components["schemas"]["ReviewReason"][];
            /** Edited At */
            edited_at?: string | null;
            /** Favourited At */
            favourited_at?: string | null;
        };
        /** ReviewItemDocument */
        ReviewItemDocument: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** ReviewItemExtraction */
        ReviewItemExtraction: {
            /** Schema */
            schema: string;
            /** Yield */
            yield: string | null;
            /** Top Ingredients */
            top_ingredients: string[];
            /** Confidence Overall */
            confidence_overall: number | null;
        };
        /** ReviewItemListResponse */
        ReviewItemListResponse: {
            /** Review Items */
            review_items: components["schemas"]["ReviewItem"][];
        };
        /**
         * ReviewItemSourcePages
         * @description Min/max page bounds resolved from the item's own source spans.
         *
         *     ``needs_review`` items have no chunks, so these come straight from
         *     ``KnowledgeItem.source_span_ids`` locators; both ``None`` when nothing
         *     resolves.
         */
        ReviewItemSourcePages: {
            /** Page Start */
            page_start: number | null;
            /** Page End */
            page_end: number | null;
        };
        /**
         * ReviewReason
         * @description One reason an item needs review (Epic 21.1, D3).
         *
         *     ``code`` is a stable machine code (a ``validate_soft`` warning code, or
         *     the ``llm_warning`` envelope for non-canonical strings); ``message`` is a
         *     presentation-layer human label.
         */
        ReviewReason: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Value */
            value?: number | null;
            /** Threshold */
            threshold?: number | null;
            /** Ingredient Positions */
            ingredient_positions?: number[] | null;
        };
        /** ReviewRequest */
        ReviewRequest: {
            decision: components["schemas"]["ReviewDecision"];
        };
        /** ReviewResponse */
        ReviewResponse: {
            knowledge_item: components["schemas"]["ReviewedKnowledgeItem"];
            /** Decision */
            decision: string;
        };
        /**
         * ReviewThresholds
         * @description The current soft-validation bounds, so the UI can mark per-line scores
         *     (steps, fields) the item-level reasons do not individually name. Shipped
         *     only on ``needs_review`` items.
         */
        ReviewThresholds: {
            /** Overall */
            overall: number;
            /** Boundary */
            boundary: number;
            /** Normalization */
            normalization: number;
        };
        /** ReviewedKnowledgeItem */
        ReviewedKnowledgeItem: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Status */
            status: string;
        };
        /** SearchFilters */
        SearchFilters: {
            /**
             * Item Type
             * @default recipe
             */
            item_type: string | null;
            /**
             * Document Ids
             * @default []
             */
            document_ids: string[];
            /**
             * Exclude Needs Review
             * @default true
             */
            exclude_needs_review: boolean;
        };
        /** SearchRequestBody */
        SearchRequestBody: {
            /** Query */
            query: string;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /**
             * @default {
             *       "item_type": "recipe",
             *       "document_ids": [],
             *       "exclude_needs_review": true
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /** Limit */
            limit?: number | null;
            /**
             * Include Debug
             * @default false
             */
            include_debug: boolean;
            /**
             * Mode
             * @default hybrid
             */
            mode: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["KnowledgeItemResult"][];
            debug?: components["schemas"]["RetrievalDebugInfo"] | null;
        };
        /** SourceCitation */
        SourceCitation: {
            /** Source Span Id */
            source_span_id: string;
            /** Label */
            label: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            } | null;
        };
        /** StructuredPreview */
        StructuredPreview: {
            /** Schema */
            schema: string;
            /** Yield */
            yield: string | null;
            /** Top Ingredients */
            top_ingredients: string[];
        };
        /** UploadIngestion */
        UploadIngestion: {
            /** Status */
            status: string;
        };
        /** UploadResponse */
        UploadResponse: {
            document: components["schemas"]["DocumentResponse"];
            ingestion: components["schemas"]["UploadIngestion"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                category?: string | null;
                status?: string | null;
                source_type?: string | null;
                limit?: string | null;
                offset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_batch_api_v1_documents_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_batch_api_v1_documents_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_status_api_v1_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_api_v1_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReprocessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_v1_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compose_menu_api_v1_menus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_item_api_v1_knowledge_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_item_api_v1_knowledge_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_item_api_v1_knowledge_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_knowledge_item_api_v1_knowledge_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_knowledge_items_api_v1_documents__document_id__knowledge_items_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: string | null;
                offset?: string | null;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favourite_api_v1_knowledge_items__item_id__favourite_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavouriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favourite_api_v1_knowledge_items__item_id__favourite_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favourites_api_v1_favourites_get: {
        parameters: {
            query?: {
                limit?: string | null;
                offset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_items_api_v1_review_items_get: {
        parameters: {
            query?: {
                document_id?: string | null;
                limit?: string | null;
                offset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_knowledge_item_api_v1_knowledge_items__item_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
