/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Documents Batch
         * @description Upload a cohort of PDFs and defer extraction into the Anthropic batch path.
         *
         *     Each file is created exactly as ``POST /documents`` does (shared helper), but
         *     enqueued with ``batch_mode=True`` so ``process_document`` registers windows
         *     instead of running synchronous extraction. Per-file failures (non-PDF, etc.)
         *     yield an ``error`` item without aborting the cohort.
         *
         *     **Refuses creation unless the Anthropic batch path is enabled** (``llm_provider
         *     == "anthropic"`` + a key): otherwise the created docs would register windows
         *     that no submitter could ever drain, stranding them in ``EXTRACTING_ITEMS``
         *     (DECISIONS #3; Codex round-1 #2).
         */
        post: operations["upload_documents_batch_api_v1_documents_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Status
         * @description Report ingestion progress for a document.
         *
         *     For a non-terminal doc the in-flight version is the highest existing span
         *     version (Epic 11.2, DECISIONS #5) — ``max + 1`` work for a new_source_version
         *     run already shows up as v(new) spans, while initial ingestion / a reuse run
         *     stays on the current version; it defaults to ``1`` before any span exists.
         *     Progress is suppressed only when the in-flight version equals the *already
         *     active* version — a reuse reprocess re-runs over existing spans without
         *     creating new ones, so the surviving spans are not this run's progress. A
         *     new_source_version run (in-flight > active) and initial ingestion (no active
         *     version) both report the in-flight version's spans. Terminal docs report their
         *     active version's final counts (a failed doc with active=null gets (0, None)).
         */
        get: operations["get_document_status_api_v1_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Document */
        post: operations["reprocess_document_api_v1_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Documents */
        post: operations["search_documents_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_v1_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Item */
        get: operations["get_knowledge_item_api_v1_knowledge_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerOptions */
        AnswerOptions: {
            /**
             * Style
             * @default recommendation
             */
            style: string;
            /**
             * Include Results
             * @default false
             */
            include_results: boolean;
            /**
             * Include Debug
             * @default false
             */
            include_debug: boolean;
        };
        /** AnswerRequestBody */
        AnswerRequestBody: {
            /** Query */
            query: string;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /**
             * @default {
             *       "item_type": "recipe",
             *       "document_ids": [],
             *       "exclude_needs_review": true
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /**
             * @default {
             *       "mode": "hybrid"
             *     }
             */
            retrieval: components["schemas"]["AnswerRetrievalOptions"];
            /**
             * @default {
             *       "style": "recommendation",
             *       "include_results": false,
             *       "include_debug": false
             *     }
             */
            answer: components["schemas"]["AnswerOptions"];
        };
        /** AnswerRetrievalOptions */
        AnswerRetrievalOptions: {
            /**
             * Mode
             * @default hybrid
             */
            mode: string;
            /** Limit */
            limit?: number | null;
        };
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** File */
            file?: string | null;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /** Title */
            title?: string | null;
            /** Author */
            author?: string | null;
            /** Language */
            language?: string | null;
        };
        /** Body_upload_documents_batch_api_v1_documents_batch_post */
        Body_upload_documents_batch_api_v1_documents_batch_post: {
            /** Files */
            files: string[];
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /** Language */
            language?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ReprocessRequest */
        ReprocessRequest: {
            /** Mode */
            mode: string;
            /** Reason */
            reason?: string | null;
        };
        /** SearchFilters */
        SearchFilters: {
            /**
             * Item Type
             * @default recipe
             */
            item_type: string | null;
            /**
             * Document Ids
             * @default []
             */
            document_ids: string[];
            /**
             * Exclude Needs Review
             * @default true
             */
            exclude_needs_review: boolean;
        };
        /** SearchRequestBody */
        SearchRequestBody: {
            /** Query */
            query: string;
            /**
             * Category
             * @default recipes
             */
            category: string;
            /** Subcategory */
            subcategory?: string | null;
            /**
             * @default {
             *       "item_type": "recipe",
             *       "document_ids": [],
             *       "exclude_needs_review": true
             *     }
             */
            filters: components["schemas"]["SearchFilters"];
            /** Limit */
            limit?: number | null;
            /**
             * Include Debug
             * @default false
             */
            include_debug: boolean;
            /**
             * Mode
             * @default hybrid
             */
            mode: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                category?: string | null;
                status?: string | null;
                source_type?: string | null;
                limit?: string | null;
                offset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_batch_api_v1_documents_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_batch_api_v1_documents_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_status_api_v1_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_api_v1_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_v1_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_item_api_v1_knowledge_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
